require('dotenv').config();

export default {
    token: process.env.TOKEN,
    proxy: process.env.PROXY,

    userAgent: process.env.USER_AGENT,
    xSessionKey: process.env.X_SESSION_KEY,

    filesPerChannel: 9999,
    maxSizePerChannel: 1000 * 1024 * 1024, // 1MB = 1024 * 1024,

    rootUrl: 'https://www.radiotunes.com/_papi/v1/radiotunes/routines/channel/',

    channels: [
        // =========================
        // DI.FM
        // =========================

        // { id: 438, name: 'Synthwave' },
        // { id: 403, name: 'atmosphericbreaks' },
        // { id: 290, name: 'bassnjackinhouse' },
        // { id: 289, name: 'bassline' },
        // { id: 325, name: 'bigbeat' },
        // { id: 209, name: 'bigroomhouse' },
        // { id: 15, name: 'breaks' },
        // { id: 400, name: 'chillntropicalhouse' },
        // { id: 224, name: 'chillhop' },
        // { id: 3, name: 'chillout' },
        // { id: 68, name: 'chilloutdreams' },
        // { id: 275, name: 'chillstep' },
        // { id: 69, name: 'classiceurodance' },
        // { id: 183, name: 'classiceurodisco' },
        // { id: 90, name: 'classictrance' },
        // { id: 125, name: 'classicvocaltrance' },
        // { id: 177, name: 'clubdubstep' },
        // { id: 70, name: 'club' },
        // { id: 181, name: 'darkdnb' },
        // { id: 346, name: 'darkpsytrance' },
        // { id: 174, name: 'deephouse' },
        // { id: 137, name: 'deepnudisco' },
        // { id: 182, name: 'deeptech' },
        // { id: 353, name: 'detroithousentechno' },
        // { id: 92, name: 'discohouse' },
        // { id: 10, name: 'djmixes' },
        // { id: 180, name: 'downtempolounge' },
        // { id: 13, name: 'drumandbass' },
        // { id: 291, name: 'drumstep' },
        // { id: 348, name: 'dub' },
        // { id: 355, name: 'dubtechno' },
        // { id: 91, name: 'dubstep' },
        // { id: 326, name: 'ebm' },
        // { id: 208, name: 'eclectronica' },
        // { id: 56, name: 'electro' },
        // { id: 327, name: 'electroswing' },
        // { id: 280, name: 'electronicpioneers' },
        // { id: 347, name: 'electronics' },
        // { id: 286, name: 'electropop' },
        // { id: 175, name: 'epictrance' },
        // { id: 6, name: 'eurodance' },
        // { id: 58, name: 'funkyhouse' },
        // { id: 424, name: 'futurebass' },
        // { id: 292, name: 'futuregarage' },
        // { id: 53, name: 'futuresynthpop' },
        // { id: 16, name: 'gabber' },
        // { id: 198, name: 'glitchhop' },
        // { id: 8, name: 'goapsy' },
        // { id: 176, name: 'handsup' },
        // { id: 5, name: 'harddance' },
        // { id: 276, name: 'hardtechno' },
        // { id: 9, name: 'hardcore' },
        // { id: 60, name: 'hardstyle' },
        // { id: 4, name: 'house' },
        // { id: 350, name: 'idm' },
        // { id: 404, name: 'indiebeats' },
        // { id: 351, name: 'indiedance' },
        // { id: 349, name: 'jazzhouse' },
        // { id: 293, name: 'jungle' },
        // { id: 117, name: 'latinhouse' },
        // { id: 105, name: 'liquiddnb' },
        // { id: 184, name: 'liquiddubstep' },
        // { id: 352, name: 'liquidtrap' },
        // { id: 11, name: 'lounge' },
        // { id: 210, name: 'mainstage' },
        // { id: 402, name: 'melodicprogressive' },
        // { id: 59, name: 'minimal' },
        // { id: 294, name: 'nightcore' },
        // { id: 295, name: 'nudisco' },
        // { id: 124, name: 'oldschoolacid' },
        // { id: 104, name: 'oldschoolhouse' },
        // { id: 296, name: 'oldschoolrave' },
        // { id: 14, name: 'classictechno' },
        // { id: 7, name: 'progressive' },
        // { id: 178, name: 'progressivepsy' },
        // { id: 285, name: 'psybient' },
        // { id: 67, name: 'psychill' },
        // { id: 213, name: 'russianclubhits' },
        // { id: 47, name: 'soulfulhouse' },
        // { id: 64, name: 'spacemusic' },
        // { id: 438, name: 'synthwave' },
        // { id: 66, name: 'techhouse' },
        // { id: 36, name: 'techno' },
        // { id: 1, name: 'trance' },
        // { id: 57, name: 'tribalhouse' },
        // { id: 215, name: 'umfradio' },
        // { id: 288, name: 'undergroundtechno' },
        // { id: 142, name: 'vocalchillout' },
        // { id: 445, name: 'vocalhouse' },
        // { id: 278, name: 'vocallounge' },
        // { id: 2, name: 'vocaltrance' },

        // =========================
        // RadioTunes
        // =========================

        //{ id: 440, name: '00s Rock' },
        // { id: 441, name: '70s Rock' },
        // { id: 171, name: '90s Rock' },
        // { id: 437, name: '00s Country' },
        // { id: 436, name: '90s Country' },
        // { id: 61, name: 'Love Music' },
        // { id: 21, name: 'Top Hits' },
        // { id: 20, name: 'Smooth Jazz' },
        // { id: 22, name: '80s Hits' },
        // { id: 46, name: 'Classic Rock' },
        // { id: 52, name: 'Solo Piano' },
        // { id: 18, name: 'New Age' },
        // { id: 111, name: 'Vocal Smooth Jazz' },
        // { id: 120, name: 'Relaxation' },
        // { id: 118, name: "Smooth Jazz 24'7" },
        // { id: 132, name: 'Soft Rock' },
        // { id: 173, name: 'Smooth Lounge' },
        // { id: 197, name: 'Café de Paris' },
        // { id: 422, name: 'Chill & Tropical House' },
        // { id: 24, name: '70s Hits' },
        // { id: 297, name: 'Mellow Smooth Jazz' },
        // { id: 39, name: 'Oldies' },
        // { id: 109, name: 'Dreamscapes' },
        // { id: 17, name: 'Mostly Classical' },
        // { id: 141, name: '80s Rock Hits' },
        // { id: 334, name: 'Lounge' },
        // { id: 228, name: '80s Dance' },
        // { id: 41, name: 'Uptempo Smooth Jazz' },
        // { id: 358, name: '00s Hits' },
        // { id: 188, name: 'Mellow Jazz' },
        // { id: 48, name: 'DaTempo Lounge' },
        // { id: 121, name: 'Vocal New Age' },
        // { id: 49, name: 'Alternative Rock' },
        // { id: 407, name: 'Smooth Beats' },
        // { id: 423, name: 'Indie Dance' },
        // { id: 23, name: 'Roots Reggae' },
        // { id: 71, name: 'Dance Hits' },
        // { id: 25, name: 'Country' },
        // { id: 119, name: 'Nature' },
        // { id: 54, name: 'Bossa Nova' },
        // { id: 299, name: '00s R&B' },
        // { id: 303, name: 'Meditation' },
        // { id: 186, name: '90s Hits' },
        // { id: 229, name: '90s R&B' },
        // { id: 214, name: '60s Hits' },
        // { id: 19, name: 'Classical Guitar' },
        // { id: 273, name: 'Old School Funk & Soul' },
        // { id: 128, name: 'Modern Blues' },
        // { id: 27, name: 'Salsa' },
        // { id: 420, name: 'Romántica Latina' },
        // { id: 187, name: 'Smooth Bossa Nova' },
        // { id: 298, name: 'Dave Koz & Friends' },
        // { id: 417, name: 'Latin Pop Hits' },
        // { id: 406, name: 'Sleep Relaxation' },
        // { id: 55, name: 'Piano Jazz' },
        // { id: 227, name: '60s Rock' },
        // { id: 414, name: 'Bolero' },
        // { id: 50, name: 'Movie Soundtracks' },
        // { id: 108, name: 'Romantica' },
        // { id: 335, name: 'Vocal Chillout' },
        // { id: 43, name: 'World' },
        // { id: 330, name: 'Chillout' },
        // { id: 336, name: 'Vocal Lounge' },
        // { id: 343, name: 'Classical Period' },
        // { id: 331, name: 'Downtempo Lounge' },
        // { id: 305, name: 'Urban Pop Hits' },
        // { id: 93, name: 'American Songbook' },
        // { id: 51, name: 'Contemporary Christian' },
        // { id: 354, name: '80s Alt & New Wave' },
        // { id: 129, name: 'Metal' },
        // { id: 306, name: 'Relaxing Ambient Piano' },
        // { id: 139, name: 'Pop Rock' },
        // { id: 356, name: 'Blues Rock' },
        // { id: 130, name: 'Hard Rock' },
        // { id: 322, name: 'Slow R&B' },
        // { id: 342, name: 'Baroque Period' },
        // { id: 344, name: 'Mozart' },
        // { id: 26, name: 'Jazz Classics' },
        // { id: 72, name: 'Bebop Jazz' },
        // { id: 42, name: 'Urban Hits' },
        // { id: 38, name: 'Classic Hip-Hop' },
        // { id: 140, name: 'Club Bollywood' },
        // { id: 415, name: 'Cuban Lounge' },
        // { id: 94, name: 'Classical Piano Trios' },
        // { id: 329, name: 'Ambient' },
        // { id: 307, name: 'Disco Party' },
        // { id: 37, name: 'Indie Rock' },
        // { id: 131, name: 'Modern Rock' },
        // { id: 418, name: 'Latin Rock' },
        // { id: 332, name: 'EDM Fest' },
        // { id: 333, name: 'EuroDance' },
        // { id: 202, name: 'Classic Motown' },
        // { id: 345, name: 'Romantic Period' },
        // { id: 110, name: 'Jpop' },
        // { id: 304, name: 'Reggaeton' },
        // { id: 416, name: 'Flamenco' },
        // { id: 421, name: 'Tango' },
        // { id: 419, name: 'Norteña' },
    ],
};
