require('dotenv').config();

export default {
    token: process.env.TOKEN,
    proxy: process.env.PROXY,

    filesPerChannel: 9999,
    maxSizePerChannel: 1000 * 1024 * 1024, // 1MB = 1024 * 1024

    channels: [
        { id: 440, name: '00s Rock' },
        { id: 441, name: '70s Rock' },
        { id: 171, name: '90s Rock' },
        // { id: 437, name: '00s Country' },
        // { id: 436, name: '90s Country' },
        // { id: 61, name: 'Love Music' },
        { id: 21, name: 'Top Hits' },
        // { id: 20, name: 'Smooth Jazz' },
        { id: 22, name: '80s Hits' },
        { id: 46, name: 'Classic Rock' },
        // { id: 52, name: 'Solo Piano' },
        // { id: 18, name: 'New Age' },
        // { id: 111, name: 'Vocal Smooth Jazz' },
        // { id: 120, name: 'Relaxation' },
        // { id: 118, name: "Smooth Jazz 24'7" },
        // { id: 132, name: 'Soft Rock' },
        // { id: 173, name: 'Smooth Lounge' },
        // { id: 197, name: 'Café de Paris' },
        { id: 422, name: 'Chill & Tropical House' },
        { id: 24, name: '70s Hits' },
        // { id: 297, name: 'Mellow Smooth Jazz' },
        // { id: 39, name: 'Oldies' },
        // { id: 109, name: 'Dreamscapes' },
        { id: 17, name: 'Mostly Classical' },
        // { id: 141, name: '80s Rock Hits' },
        // { id: 334, name: 'Lounge' },
        // { id: 228, name: '80s Dance' },
        // { id: 41, name: 'Uptempo Smooth Jazz' },
        { id: 358, name: '00s Hits' },
        // { id: 188, name: 'Mellow Jazz' },
        // { id: 48, name: 'DaTempo Lounge' },
        // { id: 121, name: 'Vocal New Age' },
        // { id: 49, name: 'Alternative Rock' },
        // { id: 407, name: 'Smooth Beats' },
        { id: 423, name: 'Indie Dance' },
        // { id: 23, name: 'Roots Reggae' },
        // { id: 71, name: 'Dance Hits' },
        { id: 25, name: 'Country' },
        // { id: 119, name: 'Nature' },
        // { id: 54, name: 'Bossa Nova' },
        // { id: 299, name: '00s R&B' },
        // { id: 303, name: 'Meditation' },
        { id: 186, name: '90s Hits' },
        // { id: 229, name: '90s R&B' },
        // { id: 214, name: '60s Hits' },
        // { id: 19, name: 'Classical Guitar' },
        // { id: 273, name: 'Old School Funk & Soul' },
        // { id: 128, name: 'Modern Blues' },
        // { id: 27, name: 'Salsa' },
        // { id: 420, name: 'Romántica Latina' },
        // { id: 187, name: 'Smooth Bossa Nova' },
        // { id: 298, name: 'Dave Koz & Friends' },
        // { id: 417, name: 'Latin Pop Hits' },
        // { id: 406, name: 'Sleep Relaxation' },
        // { id: 55, name: 'Piano Jazz' },
        // { id: 227, name: '60s Rock' },
        // { id: 414, name: 'Bolero' },
        // { id: 50, name: 'Movie Soundtracks' },
        // { id: 108, name: 'Romantica' },
        { id: 335, name: 'Vocal Chillout' },
        // { id: 43, name: 'World' },
        // { id: 330, name: 'Chillout' },
        // { id: 336, name: 'Vocal Lounge' },
        // { id: 343, name: 'Classical Period' },
        // { id: 331, name: 'Downtempo Lounge' },
        // { id: 305, name: 'Urban Pop Hits' },
        // { id: 93, name: 'American Songbook' },
        // { id: 51, name: 'Contemporary Christian' },
        { id: 354, name: '80s Alt & New Wave' },
        { id: 129, name: 'Metal' },
        // { id: 306, name: 'Relaxing Ambient Piano' },
        // { id: 139, name: 'Pop Rock' },
        // { id: 356, name: 'Blues Rock' },
        { id: 130, name: 'Hard Rock' },
        // { id: 322, name: 'Slow R&B' },
        // { id: 342, name: 'Baroque Period' },
        // { id: 344, name: 'Mozart' },
        // { id: 26, name: 'Jazz Classics' },
        // { id: 72, name: 'Bebop Jazz' },
        { id: 42, name: 'Urban Hits' },
        { id: 38, name: 'Classic Hip-Hop' },
        // { id: 140, name: 'Club Bollywood' },
        // { id: 415, name: 'Cuban Lounge' },
        // { id: 94, name: 'Classical Piano Trios' },
        // { id: 329, name: 'Ambient' },
        // { id: 307, name: 'Disco Party' },
        { id: 37, name: 'Indie Rock' },
        // { id: 131, name: 'Modern Rock' },
        // { id: 418, name: 'Latin Rock' },
        // { id: 332, name: 'EDM Fest' },
        { id: 333, name: 'EuroDance' },
        // { id: 202, name: 'Classic Motown' },
        // { id: 345, name: 'Romantic Period' },
        { id: 110, name: 'Jpop' },
        // { id: 304, name: 'Reggaeton' },
        // { id: 416, name: 'Flamenco' },
        // { id: 421, name: 'Tango' },
        // { id: 419, name: 'Norteña' },
    ],
};
